const GRAPE_HOST = "127.0.0.1";
const GRAPH_DHT_PORT = 20001;
const GRAPH_API_PORT = 30001;
const SREVER_TIMEOUT = 300000;
const CLIENT_REQUEST_TIMEOUT = 10000;
const SERVICE_NAME = "orderService";

module.exports = {
  GRAPE_HOST,
  GRAPH_DHT_PORT,
  GRAPH_API_PORT,
  SREVER_TIMEOUT,
  CLIENT_REQUEST_TIMEOUT,
  SERVICE_NAME,
};
